---
title: "人才培养"
---

## 2024 届毕业生
### 潘美琪

* **专业**：智慧能源创新学院
* **去向**：国网无锡供电公司
* **荣誉与奖励**：
    * 智慧能源创新学院研一唯一国奖获得者（2022年度）
* **论文发表**：
    1. 潘美琪, 贺兴, 艾芊, 等.新型配电系统分布式资源调度研究现状与展望[J/OL]. 电网技术:1-16[2023-12-11]. (已发表)
    2. 潘美琪, 贺兴. 基于TimeGAN-Stacking的风电机组变桨系统故障诊断方法, 太阳能学报. (已录用)
    3. 潘美琪, 贺兴. 基于零样本学习的风机故障诊断方法, 上海交通大学学报. (已录用)
    4. 贺兴, 潘美琪, 唐跃中, 等.基于数字孪生与元宇宙的能源互联网认知系统论(二)：面向复杂系统涌现现象的虚拟仿真推演框架[J/OL]. 中国电机工程学报: 1-13[2023-12-11]. (已发表)
    5. 贺兴, 潘美琪, 艾芊. 小样本学习技术在新型电力系统的应用与挑战[J/OL]. 电力系统自动化: 1-9[2023-12-11]. (已发表)

### 韩烨宸
* **专业**：电气工程系
* **去向**：国网无锡供电公司
* **论文发表**：
    1. 韩烨宸, 贺兴, 艾芊. 基于GRU-EEMD算法的非侵入式配电网功率欠定盲源分离[J]. 电力系统自动化, 2023, 47(14): 64-71.
    2. R. Cheng, Y. Han, T. Mao and B. Zhou, etc. A GRU based Flexible Resource Identification Approach with Small Dataset [C]. 2022 7th Asia Conference on Power and Electrical Engineering (ACPEE), Hangzhou, China, 2022, pp. 146-151.
    3. 贺兴, 唐跃中, 韩烨宸, 等. 基于数字孪生与元宇宙的能源互联网认知系统论(三)：复杂系统群智调控理论及其框架[J/OL]. 中国电机工程学报: 1-12[2024-04-30].

## 往年优秀毕业生
（部分，排名不分先后）

| 姓名 | 院校 | 职位 |
|---|---|---|
| 王兆宇 | Iowa State University, USA | Professor |
| 顾承红 | University of Bath, UK | Reader（教授级别）
| 贺兴 | 上海交通大学 | 副研究员 |
| 高扬 | 上海交通大学 | 助理研究员 |
| 李嘉媚 | 上海交通大学 | 助理研究员 |
| 吕天光 | 哈佛大学<br/>山东大学 | 博士后<br/>教授、博导 |
| 范松丽 | 苏州科技大学 | 讲师 |
: 国内外高校就职 {#tbl-student_gaoxiao}
