---
title: "论文归档规则"
author: "ZZY"
date: "2024-07-22"
categories: [rule, paper]
---

本文为提交归档论文及相关材料的规则。

# Rules of Archiving / 论文归档规则

You must be familiar with markdown grammar. This file is a tutorial and should not be included in your archive.

请熟悉 markdown 语法。本文件为归档教程，无须出现在您的存档中。

## Naming / 命名

The naming rules are listed as follows.

存档命名规则如下。

```
[year / 年份]-[author / 作者]-[topic / 论文主题]-[status / 投稿状态]
```

* \[year\]: The year of the latest status update.
* \[年份\]：投稿状态最后一次更新所在年份；

- \[author\]: The actual author of the paper.
- \[作者\]：该论文的实际作者；

* \[topic\]: The topic is less than 20 characters long, and consists of only English letters and numbers.
* \[论文主题\]：论文主题长度应小于 20 字符，且仅包含英文字母和数字；

- \[status\]: The status includes "WIP", "submitted", "accepted", "published", "rejected", etc.
- \[投稿状态\]：投稿状态包括：“未投稿”、“在投”、“已录用”、“已发表”和“被拒”等.

## Document Structure / 文档结构

All files are divided into 3 categories and saved in corresponding folders.

所有文件分为 3 类，并存储在对应的文件夹中。

| Category / 类别           | Description / 描述                                           |
| ------------------------- | ------------------------------------------------------------ |
| paper<br>论文             | Including your paper, citation, figures, reviews, etc.<br>包括论文原文、文献引用、论文中使用的图片、审稿意见等 |
| code<br>代码              | Including your code, dataset, tutorial, etc.<br>包括代码文件、数据文件、使用说明等 |
| supplementary<br>补充材料 | Other documents such as reference papers, slides, etc.<br>其他补充材料，如参考文献、展示幻灯片等 |

If you have multiple versions of files, you may save them in different folders and add the version number in the folder name. Please do not save them in one folder, which would confuse others.

如果您有多个版本的文件，请将它们存储在不同文件夹中，并在文件夹名字后加上版本号。请不要将不同版本的文件存储在同一文件夹中，这会为他人带来困扰。

### Structure of `paper` Folder

* The figures and other materials must be saved in `./figures/` folder.
* 论文中使用的图片等素材应存储在 `./figures/` 文件夹中；

- The submitted files should backup in `../paper-submission/` folder.
- 投稿版本应在 `../paper-submission/` 文件夹中额外备份。

### Structure of `code` Folder

* An introduction file must be included.
* 必须包含项目介绍文件；

- All data files (including the **output** of your program) must be saved in `./data/` folder and separated from code file.
- 数据文件（包括程序的**输出**）应存储在 `./data/` 文件夹中，与代码文件分开；

* The initial version of all data files must be kept. The cleaned data should not overwrite initial data, and it should be saved as a new file.
* 所有数据的初始版本必须保留，清洗后的数据不能直接覆盖原始数据，而应该另存为新文件；

- <font color=red>**Absolute paths are not allowed in the code!**</font>
- <font color=red>**代码中不要包含绝对路径！**</font>（我不希望看到您的用户名被硬编码进程序，会很尬）

* The LICENSE file of others' open source code must be kept.
* 使用他人的开源代码必须保留 LICENSE 文件
