---
title: "承担项目"
---

| 序号 | 项目名称 | 编号 | 主持人 |
|-|-------|--|--|
| 1 | 分布式能源虚拟孪生体的聚合行为及其涌现现象研究 | 52277111 | 贺兴 | 
| 2 | 基于随机矩阵理论和深度学习技术融合的配电网故障高维判据构建及其智能诊断方法研究 | 51907121 | 贺兴 |
| 3 | 基于非凸正则化的高维协方差矩阵估计方法研究 | 61871265 | 贺兴（参与） |
| 4 | 区域能源网中广义虚拟电厂构建，运行机理与优化调度模式研究 | 51577115 | 艾芊 |
| 5 | 基于免疫移动多智能体系统的微电网智能控制与互动性研究 | 51077092 | 艾芊 |
| 6 | 高比例分布式新能源发电分层自治控制及集群经济运行研究  | U176620216 | 艾芊 |
| 7 | 基于能源细胞-组织架构的区域能源网分层调控、互动机制与市场交易研究 | U1866206<br/>联合重点 | 艾芊（参与） |
: 主持和参与相关国家自然科学基金项目 7 项 {#tbl-project_gzr}

| 序号 | 项目名称 | 编号 | 主持人 |
|-|------|--|---|
| 1 | 虚拟电厂分布式协同互动调度与运行控制技术 | 2021YFB2401204 | 贺兴（子课题主持） |
| 2 | 能源互联网云边端数字孪生智能体联合态势感知 | 21DZ1208304 | 贺兴（子课题主持） |
| 3 | 面向新型电力系统的数字孪生电网仿真服务架构及实现典型模式研究 | 22H010101576 | 	贺兴（主持） |
| 4 | 全息城市背景下的能源数据赋能提智支撑工作 | 22H010104339 | 贺兴（主持） |
| 5 | 虚拟电厂分层互动模式与区块链可信交易技术 | 2021YFB2401203 | 艾芊（主持） |
| 6 | 多参与主体的工业园区互动机制及关键技术研究 | 2016YFB0901302 | 艾芊（参与） |
| 7 | 基于多能协同的源-网-荷-储智能调度方法与系 | 2016YFB0901304 | 艾芊（参与） |
| 8 | 以大规模可再生能源利用为特征的智能电网综合示范工程 | 2013BAA01B04 | 艾芊（参与） |
| 9 | 电动汽车智能充放储一体化电站系统及工程示范 | 2011AA05A108 | 艾芊（参与） |
| 10 | 物联网环境下基于云-边计算的需求侧资源协同优化与智能调节关键技术研究 | 5700201916469A | 高扬（参与） |
| 11 | 基于多能互补的微网规划与运行控制技术研究及应用 | 52060018000N | 高扬（参与） |
: 主持和参与相关国家863/重点研发计划/国网科技项目 11 项 {#tbl-project_zhongdian}

| 序号 | 名称 | 类型 |
|-|--------|---|
| 1 | 分布式能源虚拟孪生体的聚合行为及其涌现现象研究(2023-2026) | 国家自然基金（面上） |
| 2 | 基于随机矩阵理论和深度学习技术融合的配电网故障高维判据构建及其智能诊断方法研究(2020-2022) | 国家自然基金（青年） |
| 3 | 基于数字孪生和态势感知技术的区域能源网最佳行为决策研究(2021-2022)<br/>课题3：基于高维相关性分析的因素影响力分析及关键因素溯源 | 国网总部科技项目 |
: 基金 {#tbl-project_jijin}
